# Generated by Django 2.2.5 on 2022-01-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('gu', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('menu', models.TextField()),
            ],
        ),
    ]
