# Generated by Django 2.2.5 on 2022-01-24 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'managed': False},
        ),
    ]
