# Generated by Django 2.2.5 on 2022-01-19 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_armyshop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armyshop',
            options={'managed': False, 'ordering': ['-id', 'name']},
        ),
    ]
